import type { Category } from "@/components/gear/types";

export const affiliatePlaceholderUrl = "#";

export const categories: Category[] = [
  {
    id: "category-1",
    title: "Communication Gear",
    products: [
      {
        bestFor: "Drivers taking back-to-back calls who need clear audio without pulling over.",
        slug: "trucker-bluetooth-headset",
        comparisonBadge: "Long-Haul Pick",
        affiliateUrl: "https://a.co/d/097DJd2d",
        name: "Trucker Bluetooth Headset, Wireless Headset with Mic, Bluetooth Headsets with Dual Noise Cancelling Microphone & Mute Button, 55Hrs Working Time PC Headsets for Cell Phones, Computer, Truck Driver",
        priceRange: "$79 to $299",
        description: [
          "Protects call clarity in noisy truck cabs.",
          "Dual noise-cancelling microphones and long battery life keep dispatch, broker, and family calls clear on the road.",
        ],
        image: "https://m.media-amazon.com/images/I/61vK3WAD3LL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a trucker Bluetooth headset with microphone.",
        pros: ["All-day comfort for long dispatch calls", "Noise control tuned for truck cab environments", "Keeps hands free during route updates"],
        specs: ["Bluetooth wireless connection", "Dual noise-cancelling microphones", "Up to 55 hours working time", "Mute button with all-day comfort fit"],
      },
      {
        bestFor: "Owner-operators and team drivers who still rely on road chatter and hazard callouts.",
        slug: "cobra-cb-radio",
        comparisonBadge: "Best Value",
        affiliateUrl: "https://a.co/d/0869GBch",
        name: "Cobra 29 LTD Classic AM/FM Professional CB Radio - Easy to Operate, Emergency Radio, Instant Channel 9, 4-Watt Output, Full 40 Channels, Adjustable Receiver and SWR Calibration, Black",
        priceRange: "$89 to $189",
        description: [
          "Classic CB radio for traffic updates, weather chatter, and driver-to-driver communication.",
          "AM/FM support and instant channel access make it a dependable backup when cell service gets weak.",
        ],
        image: "https://m.media-amazon.com/images/I/714+DRSwCrL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a Cobra CB radio.",
        pros: ["Fast updates from nearby drivers", "Useful backup when cell coverage drops", "Simple hard-mounted cab setup"],
        specs: ["AM/FM 40-channel operation", "4-watt output", "Instant Channel 9 access", "SWR calibration and adjustable receiver"],
      },
    ],
  },
  {
    id: "category-2",
    title: "Safety and Lighting",
    products: [
      {
        bestFor: "Drivers handling night inspections, trailer checks, and roadside stops.",
        slug: "rechargeable-flashlights-two-pack",
        comparisonBadge: "Safety Essential",
        affiliateUrl: "https://a.co/d/04ynevEg",
        name: "Rechargeable Flashlights 2 Pack, Super Bright High Lumens Flash Light, 5 Modes Zoomable Linternas with LCD Digital Display, Powerful Handheld LED Flashlights for Home Emergencies Camping",
        priceRange: "$29 to $89",
        description: [
          "Bright rechargeable lights for inspections, trailer checks, and roadside stops.",
          "Zoom beam, multiple modes, and a digital battery display keep you ready after dark.",
        ],
        image: "https://m.media-amazon.com/images/I/91H2HARjx0L._AC_SX342_SY445_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for rechargeable handheld flashlights.",
        pros: ["Bright beam for dark yards and shoulders", "Rechargeable for repeated use", "Built to handle rough cab storage"],
        specs: ["High-lumen LED output", "Zoomable beam with 5 light modes", "Rechargeable battery with LCD display", "Water-resistant handheld design"],
      },
      {
        bestFor: "Drivers who want a faster, clearer safety setup during roadside breakdowns.",
        slug: "vantrue-n4-pro-s-dash-cam",
        comparisonBadge: "Safety Essential",
        affiliateUrl: "https://a.co/d/036B6pdj",
        name: "Vantrue N4 Pro S 4K 3 Channel Dash Cam w/Triple STARVIS 2, 4K+1080P+2.5K Front Inside Rear Dash Camera, 4+2.5K Dual Channel, HDR IR Night Vision, Voice Control, Parking Mode, GPS, Wi-Fi, Support 1TB",
        priceRange: "$39 to $79",
        description: [
          "Triple-channel dash cam records the road, cab, and rear view for stronger incident protection.",
          "4K front recording, night vision, and parking mode help protect you on and off duty.",
        ],
        image: "https://m.media-amazon.com/images/I/716nD7WzzbL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a three-channel dash camera.",
        pros: ["Provides evidence after accidents", "Captures inside and rear activity too", "Useful for insurance and fleet safety"],
        specs: ["Triple-channel coverage", "4K front plus interior and rear recording", "STARVIS 2 night vision", "GPS, Wi-Fi, and parking mode"],
      },
    ],
  },
  {
    id: "category-3",
    title: "Navigation and Tech",
    products: [
      {
        bestFor: "Drivers who need truck-safe routing and fewer surprises on unfamiliar lanes.",
        slug: "garmin-dezl-otr710",
        comparisonBadge: "Long-Haul Pick",
        affiliateUrl: "https://a.co/d/09QjIemm",
        name: "Garmin dezl OTR710, Large, Easy-to-Read 7 inch GPS Truck Navigator, Custom Routing, High-Resolution Birdseye Satellite Imagery, Directory of Trucking & Trailer Services (Renewed)",
        priceRange: "$249 to $399",
        description: [
          "Built specifically for truck drivers.",
          "Custom truck routing helps avoid low bridges, weight limits, and other costly surprises.",
        ],
        image: "https://m.media-amazon.com/images/I/71KrldruMbL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a Garmin dezl truck GPS unit.",
        pros: ["Truck-aware route guidance", "Easy-to-read mounted display", "Helps reduce wrong turns in tight corridors"],
        specs: ["7-inch display", "Truck-specific custom routing", "Birdseye satellite imagery", "Directory of trucking and trailer services"],
      },
      {
        bestFor: "Drivers wanting incident protection, insurance evidence, and peace of mind on every run.",
        slug: "ram-mounts-x-grip-phone-mount",
        comparisonBadge: "Safety Essential",
        affiliateUrl: "https://a.co/d/00UmSqVC",
        name: "RAM Mounts X-Grip Phone Mount with Twist-Lock Suction Cup Base RAP-B-166-UN7U with Medium Arm for Vehicle Windshields",
        priceRange: "$89 to $299",
        description: [
          "Locks your phone in place for navigation, dispatch apps, and hands-free visibility while driving.",
          "The suction base and X-Grip cradle hold strong even through rough truck-cab vibration.",
        ],
        image: "https://m.media-amazon.com/images/I/61HZASgrvuL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a RAM phone mount.",
        pros: ["Keeps maps at eye level", "Holds steady on rough roads", "Easy to reposition between trucks"],
        specs: ["X-Grip phone cradle", "Twist-lock suction cup base", "Medium adjustable arm", "Windshield-friendly mounting"],
      },
    ],
  },
  {
    id: "category-4",
    title: "Cab Comfort",
    products: [
      {
        bestFor: "Long-haul drivers who want cold drinks and meal prep access inside the sleeper.",
        slug: "astroai-mini-fridge",
        comparisonBadge: "Long-Haul Pick",
        affiliateUrl: "https://a.co/d/0cvt0dA7",
        name: "AstroAI Mini Fridge 2.0 Gen, 6 Liter/8 Cans Makeup Skincare Fridge 110V AC/ 12V DC Portable Thermoelectric Cooler and Warmer Little Tiny Fridge for Bedroom, Cosmetics (Dark Grey)",
        priceRange: "$49 to $149",
        description: [
          "Keep food and drinks cold on long hauls.",
          "Plugs into truck 12V outlet. Perfect for sleeper cab life.",
        ],
        image: "https://m.media-amazon.com/images/I/71Tn-81fR0L._AC_SX342_SY445_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a portable mini fridge.",
        pros: ["Cuts down on truck stop food runs", "Keeps drinks and snacks close", "Makes sleeper cab setups feel more livable"],
        specs: ["Compact sleeper-cab size", "12V truck power support", "Heats and cools food", "6 liter capacity"],
      },
      {
        bestFor: "Drivers sleeping through daylight who need quicker, deeper rest between hauls.",
        slug: "attcl-polarized-sunglasses",
        comparisonBadge: "Long-Haul Pick",
        affiliateUrl: "https://a.co/d/0caDcPX2",
        name: "ATTCL Polarized Sunglasses Men Sports: UV Protection Anti Glare Wrap Around Lightweight Metal Driving Fishing Golf Running",
        priceRange: "$29 to $79",
        description: [
          "Protect your eyes from sun glare while driving.",
          "UV400 protection and anti-glare coating make them perfect for long-haul daylight driving.",
        ],
        image: "https://m.media-amazon.com/images/I/71UjG2dprWL._AC_SX342_SY445_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for polarized wraparound driving sunglasses.",
        pros: ["Cuts harsh glare and eye fatigue", "Helps keep highway signs clearer in bright light", "Lightweight frame stays comfortable all day"],
        specs: ["Polarized UV400 protection", "Anti-glare coating", "Lightweight metal frame", "Sport wrap-around design"],
      },
    ],
  },
  {
    id: "category-5",
    title: "Power and Charging",
    products: [
      {
        bestFor: "Drivers powering laptops, chargers, and small electronics from the cab.",
        slug: "bestek-200w-power-inverter",
        comparisonBadge: "Best Value",
        affiliateUrl: "https://a.co/d/0g7k57Us",
        name: "BESTEK 200W Power Inverter, 12V DC to 110V AC Car Plug Adapter Outlet Converter with [30W USB-C]/USB-Fast Charger(18W) / Dual AC Outlets/car Charger for Laptop",
        priceRange: "$39 to $129",
        description: [
          "Turn 12V truck power into AC and USB charging for laptops, tablets, and daily cab essentials.",
          "Compact enough for the cab while keeping work and personal devices powered between stops.",
        ],
        image: "https://m.media-amazon.com/images/I/61slLuzO3FL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for a 200W power inverter.",
        pros: ["Expands what you can power on the road", "Good fit for work and downtime devices", "Rugged metal housing suits truck interiors"],
        specs: ["200W continuous power", "Dual AC outlets", "30W USB-C plus 18W USB charging", "12V DC plug adapter"],
      },
      {
        bestFor: "Drivers using navigation and dispatch apps who need the phone visible without wobble.",
        slug: "log-book-binder",
        comparisonBadge: "Best Value",
        affiliateUrl: "https://a.co/d/0g4i8YiU",
        name: "2 Pcs Log Book Binder for Truck Drivers 3 Ring Zipper Loose Leaf Log for Storing and Transporting Receipts and Important Documents in Trucks 11.4 x 8.5 Inches",
        priceRange: "$19 to $59",
        description: [
          "Keep logs, bills, receipts, permits, and trip documents organized in one zippered binder.",
          "The 3-ring setup helps drivers protect paperwork and find what they need fast during inspections or stops.",
        ],
        image: "https://m.media-amazon.com/images/I/717Z66l-WcL._AC_SY300_SX300_QL70_ML2_.jpg",
        imageAlt: "Amazon product image for truck driver log book binders.",
        pros: ["Keeps paperwork from getting lost", "Makes inspections and record checks faster", "Easy to store receipts and permits in one place"],
        specs: ["3-ring loose-leaf binder", "Zippered closure", "Sized for 11.4 x 8.5 inch documents", "Two binders included"],
      },
    ],
  },
];